### PR TITLE
Update files to enable multi-language interface

### PR DESCRIPTION
**Pull request by bovirus**
- modified py files to enable localization - replace "xxx" text strings with _("xxx")
- add tool sub-folder for localization tools and created relative batches
- add local sub-fodler for language file
- add italian language (po and mo files)

### CODE REVIEW

**Comment by digiampietro** [comment]
I merged the pull request to the new branch "pytools-localized"

**Comment by digiampietro** [comment]
After merging the pull request I got some errors executing python scripts on Linux, Il will fix them before merging on the master branch.

**Comment by bovirus** [comment]
I tried to run .py file on Windows but I get on error about a module missing.
I didn't do any changes on the modules. I modified only text strings.

**Comment by digiampietro** [comment]
I fixed all errors on confedit.py and fixed some other translations too.

By default the script will run with the default language of the OS but the user can change the language in the "Preference" menu.

Problem was related to the gettext module and correct initialization of the gettext environment.

I will fix this issue on other python scripts, "recompile" them to .exe and I will merge this branch with the master.

**Pull request merged**
